models:
  - name: bronze_category
    description: Category Raw Data Source
    columns:
      - name: category_id
        description: Natural key associated with the category
      - name: category_name
        description: Name of the category
